// K-perfume AI 향수 데이터 200개
// 올리브영 링크는 상품명 기준으로 자동 생성됩니다.
const rawPerfumes = [
  {
    id: "P001",
    name: "포맨트 시그니처 퍼퓸 코튼허그",
    brand: "포맨트",
    type: "woody",
    priceRange: "4~10만원",
    price: "39,000원",
    originalPrice: 39000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 포맨트 시그니처 퍼퓸 코튼허그입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P002",
    name: "포맨트 시그니처 퍼퓸 코튼키스",
    brand: "포맨트",
    type: "woody",
    priceRange: "4~10만원",
    price: "39,000원",
    originalPrice: 39000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 포맨트 시그니처 퍼퓸 코튼키스입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P003",
    name: "포맨트 시그니처 퍼퓸 코튼브리즈",
    brand: "포맨트",
    type: "woody",
    priceRange: "4~10만원",
    price: "39,000원",
    originalPrice: 39000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 포맨트 시그니처 퍼퓸 코튼브리즈입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P004",
    name: "포맨트 시그니처 퍼퓸 코튼배쓰",
    brand: "포맨트",
    type: "woody",
    priceRange: "4~10만원",
    price: "39,000원",
    originalPrice: 39000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 포맨트 시그니처 퍼퓸 코튼배쓰입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P005",
    name: "포맨트 시그니처 퍼퓸 코튼디어나잇",
    brand: "포맨트",
    type: "woody",
    priceRange: "4~10만원",
    price: "39,000원",
    originalPrice: 39000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 포맨트 시그니처 퍼퓸 코튼디어나잇입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P006",
    name: "포맨트 시그니처 퍼퓸 코튼딜라잇부케",
    brand: "포맨트",
    type: "floral",
    priceRange: "4~10만원",
    price: "39,000원",
    originalPrice: 39000,
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 포맨트 시그니처 퍼퓸 코튼딜라잇부케입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P007",
    name: "포맨트 시그니처 퍼퓸 코튼366",
    brand: "포맨트",
    type: "woody",
    priceRange: "4~10만원",
    price: "39,000원",
    originalPrice: 39000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 포맨트 시그니처 퍼퓸 코튼366입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P008",
    name: "포맨트 시그니처 퍼퓸 코튼선셋",
    brand: "포맨트",
    type: "woody",
    priceRange: "4~10만원",
    price: "39,000원",
    originalPrice: 39000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 포맨트 시그니처 퍼퓸 코튼선셋입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P009",
    name: "포맨트 시그니처 퍼퓸 코튼베이비",
    brand: "포맨트",
    type: "woody",
    priceRange: "4~10만원",
    price: "49,000원",
    originalPrice: 49000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 포맨트 시그니처 퍼퓸 코튼베이비입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P010",
    name: "포맨트 시그니처 퍼퓸 코튼메모리",
    brand: "포맨트",
    type: "woody",
    priceRange: "4~10만원",
    price: "49,000원",
    originalPrice: 49000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 포맨트 시그니처 퍼퓸 코튼메모리입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P011",
    name: "포맨트 시그니처 퍼퓸 코튼러브",
    brand: "포맨트",
    type: "floral",
    priceRange: "4~10만원",
    price: "49,000원",
    originalPrice: 49000,
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 포맨트 시그니처 퍼퓸 코튼러브입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P012",
    name: "포맨트 시그니처 퍼퓸 코튼플라워",
    brand: "포맨트",
    type: "floral",
    priceRange: "4~10만원",
    price: "49,000원",
    originalPrice: 49000,
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 포맨트 시그니처 퍼퓸 코튼플라워입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P013",
    name: "포맨트 시그니처 헤어퍼퓸 코튼허그",
    brand: "포맨트",
    type: "woody",
    priceRange: "1~3만원",
    price: "29,000원",
    originalPrice: 29000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 포맨트 시그니처 헤어퍼퓸 코튼허그입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P014",
    name: "포맨트 시그니처 헤어퍼퓸 코튼메모리",
    brand: "포맨트",
    type: "woody",
    priceRange: "1~3만원",
    price: "29,000원",
    originalPrice: 29000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 포맨트 시그니처 헤어퍼퓸 코튼메모리입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P015",
    name: "포맨트 시그니처 헤어퍼퓸 코튼키스",
    brand: "포맨트",
    type: "woody",
    priceRange: "1~3만원",
    price: "29,000원",
    originalPrice: 29000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 포맨트 시그니처 헤어퍼퓸 코튼키스입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P016",
    name: "포맨트 시그니처 헤어퍼퓸 코튼브리즈",
    brand: "포맨트",
    type: "woody",
    priceRange: "1~3만원",
    price: "29,000원",
    originalPrice: 29000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 포맨트 시그니처 헤어퍼퓸 코튼브리즈입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P017",
    name: "포맨트 시그니처 헤어퍼퓸 코튼배쓰",
    brand: "포맨트",
    type: "woody",
    priceRange: "1~3만원",
    price: "29,000원",
    originalPrice: 29000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 포맨트 시그니처 헤어퍼퓸 코튼배쓰입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P018",
    name: "센녹 퍼퓸 오 드 코튼",
    brand: "센녹",
    type: "musk",
    priceRange: "4~10만원",
    price: "76,000원",
    originalPrice: 76000,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 센녹 퍼퓸 오 드 코튼입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P019",
    name: "센녹 퍼퓸 애프터 레인",
    brand: "센녹",
    type: "woody",
    priceRange: "4~10만원",
    price: "76,000원",
    originalPrice: 76000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 센녹 퍼퓸 애프터 레인입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P020",
    name: "센녹 퍼퓸 선셋 머스크",
    brand: "센녹",
    type: "musk",
    priceRange: "4~10만원",
    price: "76,000원",
    originalPrice: 76000,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 센녹 퍼퓸 선셋 머스크입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P021",
    name: "센녹 퍼퓸 오렌지 플라워",
    brand: "센녹",
    type: "citrus",
    priceRange: "4~10만원",
    price: "76,000원",
    originalPrice: 76000,
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 센녹 퍼퓸 오렌지 플라워입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P022",
    name: "센녹 퍼퓸 디어 로지",
    brand: "센녹",
    type: "floral",
    priceRange: "4~10만원",
    price: "76,000원",
    originalPrice: 76000,
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 센녹 퍼퓸 디어 로지입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P023",
    name: "센녹 퍼퓸 블랙 티",
    brand: "센녹",
    type: "woody",
    priceRange: "4~10만원",
    price: "76,000원",
    originalPrice: 76000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 센녹 퍼퓸 블랙 티입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P024",
    name: "센녹 퍼퓸 화이트 셔츠",
    brand: "센녹",
    type: "musk",
    priceRange: "4~10만원",
    price: "76,000원",
    originalPrice: 76000,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 센녹 퍼퓸 화이트 셔츠입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P025",
    name: "센녹 퍼퓸 메리 미",
    brand: "센녹",
    type: "oriental",
    priceRange: "4~10만원",
    price: "76,000원",
    originalPrice: 76000,
    top: "스파이스, 만다린",
    middle: "바닐라, 플로럴",
    base: "앰버, 머스크",
    situation: "저녁/특별한 날",
    description:
      "오리엔탈 계열의 센녹 퍼퓸 메리 미입니다. 저녁/특별한 날 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P026",
    name: "센녹 퍼퓸 브리즈",
    brand: "센녹",
    type: "woody",
    priceRange: "4~10만원",
    price: "76,000원",
    originalPrice: 76000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 센녹 퍼퓸 브리즈입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P027",
    name: "센녹 퍼퓸 그린 파크",
    brand: "센녹",
    type: "musk",
    priceRange: "4~10만원",
    price: "76,000원",
    originalPrice: 76000,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 센녹 퍼퓸 그린 파크입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P028",
    name: "아뜰리에페이 퍼퓸 피치 로즈",
    brand: "아뜰리에페이",
    type: "floral",
    priceRange: "4~10만원",
    price: "39,000원",
    originalPrice: 39000,
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 아뜰리에페이 퍼퓸 피치 로즈입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P029",
    name: "아뜰리에페이 퍼퓸 화이트 플라워",
    brand: "아뜰리에페이",
    type: "floral",
    priceRange: "4~10만원",
    price: "39,000원",
    originalPrice: 39000,
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 아뜰리에페이 퍼퓸 화이트 플라워입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P030",
    name: "아뜰리에페이 퍼퓸 클린 머스크",
    brand: "아뜰리에페이",
    type: "musk",
    priceRange: "4~10만원",
    price: "39,000원",
    originalPrice: 39000,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 아뜰리에페이 퍼퓸 클린 머스크입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P031",
    name: "아뜰리에페이 퍼퓸 우디 세이지",
    brand: "아뜰리에페이",
    type: "woody",
    priceRange: "4~10만원",
    price: "39,000원",
    originalPrice: 39000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 아뜰리에페이 퍼퓸 우디 세이지입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P032",
    name: "아뜰리에페이 퍼퓸 베르가못 티",
    brand: "아뜰리에페이",
    type: "citrus",
    priceRange: "4~10만원",
    price: "39,000원",
    originalPrice: 39000,
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 아뜰리에페이 퍼퓸 베르가못 티입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P033",
    name: "아뜰리에페이 퍼퓸 바닐라 샌달",
    brand: "아뜰리에페이",
    type: "woody",
    priceRange: "4~10만원",
    price: "39,000원",
    originalPrice: 39000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 아뜰리에페이 퍼퓸 바닐라 샌달입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P034",
    name: "아뜰리에페이 퍼퓸 그린 로즈",
    brand: "아뜰리에페이",
    type: "floral",
    priceRange: "4~10만원",
    price: "39,000원",
    originalPrice: 39000,
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 아뜰리에페이 퍼퓸 그린 로즈입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P035",
    name: "아뜰리에페이 퍼퓸 코튼 블루",
    brand: "아뜰리에페이",
    type: "musk",
    priceRange: "4~10만원",
    price: "39,000원",
    originalPrice: 39000,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 아뜰리에페이 퍼퓸 코튼 블루입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P036",
    name: "끌로에 EDP 오 드 퍼퓸",
    brand: "끌로에",
    type: "floral",
    priceRange: "10만원 이상",
    price: "176,000원",
    originalPrice: 176000,
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 끌로에 EDP 오 드 퍼퓸입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P037",
    name: "끌로에 EDP 로즈 탠저린",
    brand: "끌로에",
    type: "floral",
    priceRange: "10만원 이상",
    price: "176,000원",
    originalPrice: 176000,
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 끌로에 EDP 로즈 탠저린입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P038",
    name: "끌로에 EDP 노마드",
    brand: "끌로에",
    type: "floral",
    priceRange: "10만원 이상",
    price: "176,000원",
    originalPrice: 176000,
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 끌로에 EDP 노마드입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P039",
    name: "끌로에 EDP 러브 스토리",
    brand: "끌로에",
    type: "floral",
    priceRange: "10만원 이상",
    price: "176,000원",
    originalPrice: 176000,
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 끌로에 EDP 러브 스토리입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P040",
    name: "캘빈클라인 CK One",
    brand: "캘빈클라인",
    type: "musk",
    priceRange: "4~10만원",
    price: "69,000원",
    originalPrice: 69000,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 캘빈클라인 CK One입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P041",
    name: "캘빈클라인 CK Be",
    brand: "캘빈클라인",
    type: "citrus",
    priceRange: "4~10만원",
    price: "69,000원",
    originalPrice: 69000,
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 캘빈클라인 CK Be입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P042",
    name: "캘빈클라인 CK One Essence",
    brand: "캘빈클라인",
    type: "oriental",
    priceRange: "4~10만원",
    price: "69,000원",
    originalPrice: 69000,
    top: "스파이스, 만다린",
    middle: "바닐라, 플로럴",
    base: "앰버, 머스크",
    situation: "저녁/특별한 날",
    description:
      "오리엔탈 계열의 캘빈클라인 CK One Essence입니다. 저녁/특별한 날 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P043",
    name: "캘빈클라인 CK Everyone",
    brand: "캘빈클라인",
    type: "woody",
    priceRange: "4~10만원",
    price: "69,000원",
    originalPrice: 69000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 캘빈클라인 CK Everyone입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P044",
    name: "캘빈클라인 CK All",
    brand: "캘빈클라인",
    type: "musk",
    priceRange: "4~10만원",
    price: "69,000원",
    originalPrice: 69000,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 캘빈클라인 CK All입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P045",
    name: "캘빈클라인 Eternity",
    brand: "캘빈클라인",
    type: "citrus",
    priceRange: "4~10만원",
    price: "69,000원",
    originalPrice: 69000,
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 캘빈클라인 Eternity입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P046",
    name: "캘빈클라인 Euphoria",
    brand: "캘빈클라인",
    type: "woody",
    priceRange: "4~10만원",
    price: "69,000원",
    originalPrice: 69000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 캘빈클라인 Euphoria입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P047",
    name: "캘빈클라인 CK One Night",
    brand: "캘빈클라인",
    type: "woody",
    priceRange: "4~10만원",
    price: "69,000원",
    originalPrice: 69000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 캘빈클라인 CK One Night입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P048",
    name: "캘빈클라인 CK 비 EDT",
    brand: "캘빈클라인",
    type: "oriental",
    priceRange: "4~10만원",
    price: "66,000원",
    originalPrice: 66000,
    top: "스파이스, 만다린",
    middle: "바닐라, 플로럴",
    base: "앰버, 머스크",
    situation: "저녁/특별한 날",
    description:
      "오리엔탈 계열의 캘빈클라인 CK 비 EDT입니다. 저녁/특별한 날 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P049",
    name: "캘빈클라인 CK 비 100ml",
    brand: "캘빈클라인",
    type: "floral",
    priceRange: "4~10만원",
    price: "66,000원",
    originalPrice: 66000,
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 캘빈클라인 CK 비 100ml입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P050",
    name: "캘빈클라인 CK 비 200ml",
    brand: "캘빈클라인",
    type: "oriental",
    priceRange: "4~10만원",
    price: "66,000원",
    originalPrice: 66000,
    top: "스파이스, 만다린",
    middle: "바닐라, 플로럴",
    base: "앰버, 머스크",
    situation: "저녁/특별한 날",
    description:
      "오리엔탈 계열의 캘빈클라인 CK 비 200ml입니다. 저녁/특별한 날 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P051",
    name: "나르시소 로드리게즈 포 허 퓨어 머스크 EDP",
    brand: "나르시소 로드리게즈",
    type: "musk",
    priceRange: "10만원 이상",
    price: "110,000원",
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 나르시소 로드리게즈 포 허 퓨어 머스크 EDP입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P052",
    name: "나르시소 로드리게즈 나르시소 크리스탈",
    brand: "나르시소 로드리게즈",
    type: "citrus",
    priceRange: "10만원 이상",
    price: "110,000원",
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 나르시소 로드리게즈 나르시소 크리스탈입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P053",
    name: "나르시소 로드리게즈 래디언트",
    brand: "나르시소 로드리게즈",
    type: "citrus",
    priceRange: "10만원 이상",
    price: "110,000원",
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 나르시소 로드리게즈 래디언트입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P054",
    name: "나르시소 로드리게즈 엉브레",
    brand: "나르시소 로드리게즈",
    type: "oriental",
    priceRange: "10만원 이상",
    price: "110,000원",
    top: "스파이스, 만다린",
    middle: "바닐라, 플로럴",
    base: "앰버, 머스크",
    situation: "저녁/특별한 날",
    description:
      "오리엔탈 계열의 나르시소 로드리게즈 엉브레입니다. 저녁/특별한 날 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P055",
    name: "나르시소 로드리게즈 푸드레",
    brand: "나르시소 로드리게즈",
    type: "floral",
    priceRange: "10만원 이상",
    price: "110,000원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 나르시소 로드리게즈 푸드레입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P056",
    name: "나르시소 로드리게즈 올 오브 미",
    brand: "나르시소 로드리게즈",
    type: "citrus",
    priceRange: "10만원 이상",
    price: "110,000원",
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 나르시소 로드리게즈 올 오브 미입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P057",
    name: "나르시소 로드리게즈 블루 누아르",
    brand: "나르시소 로드리게즈",
    type: "musk",
    priceRange: "10만원 이상",
    price: "110,000원",
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 나르시소 로드리게즈 블루 누아르입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P058",
    name: "루아페 EDP 화이트 애프리콧",
    brand: "루아페",
    type: "musk",
    priceRange: "4~10만원",
    price: "38,000원",
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 루아페 EDP 화이트 애프리콧입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P059",
    name: "루아페 EDP 블랑 뮤게",
    brand: "루아페",
    type: "floral",
    priceRange: "4~10만원",
    price: "38,000원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 루아페 EDP 블랑 뮤게입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P060",
    name: "루아페 EDP 디어 로즈",
    brand: "루아페",
    type: "floral",
    priceRange: "4~10만원",
    price: "38,000원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 루아페 EDP 디어 로즈입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P061",
    name: "루아페 EDP 코튼 베베",
    brand: "루아페",
    type: "musk",
    priceRange: "4~10만원",
    price: "38,000원",
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 루아페 EDP 코튼 베베입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P062",
    name: "루아페 EDP 머스크 필로우",
    brand: "루아페",
    type: "musk",
    priceRange: "4~10만원",
    price: "38,000원",
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 루아페 EDP 머스크 필로우입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P063",
    name: "루아페 EDP 피치 블룸",
    brand: "루아페",
    type: "floral",
    priceRange: "4~10만원",
    price: "38,000원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 루아페 EDP 피치 블룸입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P064",
    name: "루아페 EDP 베르가못 프레쉬",
    brand: "루아페",
    type: "citrus",
    priceRange: "4~10만원",
    price: "38,000원",
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 루아페 EDP 베르가못 프레쉬입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P065",
    name: "루아페 EDP 우디 샌달",
    brand: "루아페",
    type: "woody",
    priceRange: "4~10만원",
    price: "38,000원",
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 루아페 EDP 우디 샌달입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P066",
    name: "루아페 EDP 바닐라 문",
    brand: "루아페",
    type: "oriental",
    priceRange: "4~10만원",
    price: "38,000원",
    top: "스파이스, 만다린",
    middle: "바닐라, 플로럴",
    base: "앰버, 머스크",
    situation: "저녁/특별한 날",
    description:
      "오리엔탈 계열의 루아페 EDP 바닐라 문입니다. 저녁/특별한 날 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P067",
    name: "KEYTH 키스 오드뚜왈렛 그린",
    brand: "키스",
    type: "citrus",
    priceRange: "4~10만원",
    price: "50,000원",
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 KEYTH 키스 오드뚜왈렛 그린입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P068",
    name: "KEYTH 키스 오드뚜왈렛 화이트",
    brand: "키스",
    type: "musk",
    priceRange: "4~10만원",
    price: "50,000원",
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 KEYTH 키스 오드뚜왈렛 화이트입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P069",
    name: "KEYTH 키스 오드뚜왈렛 로즈",
    brand: "키스",
    type: "floral",
    priceRange: "4~10만원",
    price: "50,000원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 KEYTH 키스 오드뚜왈렛 로즈입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P070",
    name: "KEYTH 키스 오드뚜왈렛 머스크",
    brand: "키스",
    type: "musk",
    priceRange: "4~10만원",
    price: "50,000원",
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 KEYTH 키스 오드뚜왈렛 머스크입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P071",
    name: "KEYTH 키스 오드뚜왈렛 우디",
    brand: "키스",
    type: "woody",
    priceRange: "4~10만원",
    price: "50,000원",
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 KEYTH 키스 오드뚜왈렛 우디입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P072",
    name: "제니퍼로페즈 글로우 바이제이로 EDT",
    brand: "제니퍼로페즈",
    type: "woody",
    priceRange: "10만원 이상",
    price: "106,000원",
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 제니퍼로페즈 글로우 바이제이로 EDT입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P073",
    name: "제니퍼로페즈 스틸 EDP",
    brand: "제니퍼로페즈",
    type: "citrus",
    priceRange: "10만원 이상",
    price: "106,000원",
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 제니퍼로페즈 스틸 EDP입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P074",
    name: "제니퍼로페즈 라이브 럭스",
    brand: "제니퍼로페즈",
    type: "musk",
    priceRange: "10만원 이상",
    price: "106,000원",
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 제니퍼로페즈 라이브 럭스입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P075",
    name: "제니퍼로페즈 마이애미 글로우",
    brand: "제니퍼로페즈",
    type: "citrus",
    priceRange: "10만원 이상",
    price: "106,000원",
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 제니퍼로페즈 마이애미 글로우입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P076",
    name: "에이딕트 오 드 퍼퓸 네이키드 뮤게 313",
    brand: "에이딕트",
    type: "floral",
    priceRange: "4~10만원",
    price: "63,000원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 에이딕트 오 드 퍼퓸 네이키드 뮤게 313입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P077",
    name: "에이딕트 오 드 퍼퓸 보이드 우드",
    brand: "에이딕트",
    type: "woody",
    priceRange: "4~10만원",
    price: "63,000원",
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 에이딕트 오 드 퍼퓸 보이드 우드입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P078",
    name: "에이딕트 오 드 퍼퓸 레이어드 코튼",
    brand: "에이딕트",
    type: "musk",
    priceRange: "4~10만원",
    price: "63,000원",
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 에이딕트 오 드 퍼퓸 레이어드 코튼입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P079",
    name: "에이딕트 오 드 퍼퓸 피그 앤 머스크",
    brand: "에이딕트",
    type: "musk",
    priceRange: "4~10만원",
    price: "63,000원",
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 에이딕트 오 드 퍼퓸 피그 앤 머스크입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P080",
    name: "에이딕트 오 드 퍼퓸 그린 라이트",
    brand: "에이딕트",
    type: "floral",
    priceRange: "4~10만원",
    price: "63,000원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 에이딕트 오 드 퍼퓸 그린 라이트입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P081",
    name: "에이딕트 오 드 퍼퓸 베르가못 코드",
    brand: "에이딕트",
    type: "citrus",
    priceRange: "4~10만원",
    price: "63,000원",
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 에이딕트 오 드 퍼퓸 베르가못 코드입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P082",
    name: "에이딕트 오 드 퍼퓸 화이트 뮤스크",
    brand: "에이딕트",
    type: "musk",
    priceRange: "4~10만원",
    price: "63,000원",
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 에이딕트 오 드 퍼퓸 화이트 뮤스크입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P083",
    name: "에이딕트 솔리드 퍼퓸 네이키드 뮤게 313",
    brand: "에이딕트",
    type: "floral",
    priceRange: "4~10만원",
    price: "38,000원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 에이딕트 솔리드 퍼퓸 네이키드 뮤게 313입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P084",
    name: "에이딕트 솔리드 퍼퓸 피그 앤 머스크",
    brand: "에이딕트",
    type: "musk",
    priceRange: "4~10만원",
    price: "38,000원",
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 에이딕트 솔리드 퍼퓸 피그 앤 머스크입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P085",
    name: "에이딕트 솔리드 퍼퓸 코튼 브리즈",
    brand: "에이딕트",
    type: "musk",
    priceRange: "4~10만원",
    price: "38,000원",
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 에이딕트 솔리드 퍼퓸 코튼 브리즈입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P086",
    name: "에이딕트 솔리드 퍼퓸 우디 라이트",
    brand: "에이딕트",
    type: "woody",
    priceRange: "4~10만원",
    price: "38,000원",
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 에이딕트 솔리드 퍼퓸 우디 라이트입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P087",
    name: "랑방 에끌라 드 아르페쥬 EDP",
    brand: "랑방",
    type: "citrus",
    priceRange: "4~10만원",
    price: "70,000원",
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 랑방 에끌라 드 아르페쥬 EDP입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P088",
    name: "랑방 모던 프린세스 EDP",
    brand: "랑방",
    type: "floral",
    priceRange: "4~10만원",
    price: "70,000원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 랑방 모던 프린세스 EDP입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P089",
    name: "랑방 잔느 EDP",
    brand: "랑방",
    type: "floral",
    priceRange: "4~10만원",
    price: "70,000원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 랑방 잔느 EDP입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P090",
    name: "랑방 루머2 로즈",
    brand: "랑방",
    type: "floral",
    priceRange: "4~10만원",
    price: "70,000원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 랑방 루머2 로즈입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P091",
    name: "랑방 레 플레르 드 랑방",
    brand: "랑방",
    type: "woody",
    priceRange: "4~10만원",
    price: "70,000원",
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 랑방 레 플레르 드 랑방입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P092",
    name: "랑방 메리 미",
    brand: "랑방",
    type: "oriental",
    priceRange: "4~10만원",
    price: "70,000원",
    top: "스파이스, 만다린",
    middle: "바닐라, 플로럴",
    base: "앰버, 머스크",
    situation: "저녁/특별한 날",
    description:
      "오리엔탈 계열의 랑방 메리 미입니다. 저녁/특별한 날 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P093",
    name: "랑방 걸 인 카프리",
    brand: "랑방",
    type: "citrus",
    priceRange: "4~10만원",
    price: "70,000원",
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 랑방 걸 인 카프리입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P094",
    name: "존바바토스 아티산 EDT",
    brand: "존바바토스",
    type: "woody",
    priceRange: "10만원 이상",
    price: "149,000원",
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 존바바토스 아티산 EDT입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P095",
    name: "존바바토스 아티산 블랙 EDT",
    brand: "존바바토스",
    type: "woody",
    priceRange: "10만원 이상",
    price: "149,000원",
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 존바바토스 아티산 블랙 EDT입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P096",
    name: "존바바토스 아티산 블루 EDT",
    brand: "존바바토스",
    type: "woody",
    priceRange: "10만원 이상",
    price: "149,000원",
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 존바바토스 아티산 블루 EDT입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P097",
    name: "존바바토스 아티산 퓨어 EDT",
    brand: "존바바토스",
    type: "woody",
    priceRange: "10만원 이상",
    price: "149,000원",
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 존바바토스 아티산 퓨어 EDT입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P098",
    name: "존바바토스 XX 아티산 EDT",
    brand: "존바바토스",
    type: "woody",
    priceRange: "10만원 이상",
    price: "149,000원",
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 존바바토스 XX 아티산 EDT입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P099",
    name: "존바바토스 빈티지 EDT",
    brand: "존바바토스",
    type: "floral",
    priceRange: "10만원 이상",
    price: "149,000원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 존바바토스 빈티지 EDT입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P100",
    name: "존바바토스 아티산 EDT 40ml",
    brand: "존바바토스",
    type: "woody",
    priceRange: "4~10만원",
    price: "78,000원",
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 존바바토스 아티산 EDT 40ml입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P101",
    name: "존바바토스 아티산 블랙 EDT 40ml",
    brand: "존바바토스",
    type: "woody",
    priceRange: "4~10만원",
    price: "78,000원",
    originalPrice: 78000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 존바바토스 아티산 블랙 EDT 40ml입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P102",
    name: "존바바토스 아티산 퓨어 EDT 40ml",
    brand: "존바바토스",
    type: "woody",
    priceRange: "4~10만원",
    price: "78,000원",
    originalPrice: 78000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 존바바토스 아티산 퓨어 EDT 40ml입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P103",
    name: "어뮤즈 헤어 퍼퓸 미스트 플로럴",
    brand: "어뮤즈",
    type: "floral",
    priceRange: "4~10만원",
    price: "32,000원",
    originalPrice: 32000,
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 어뮤즈 헤어 퍼퓸 미스트 플로럴입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P104",
    name: "어뮤즈 헤어 퍼퓸 미스트 코튼",
    brand: "어뮤즈",
    type: "musk",
    priceRange: "4~10만원",
    price: "32,000원",
    originalPrice: 32000,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 어뮤즈 헤어 퍼퓸 미스트 코튼입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P105",
    name: "어뮤즈 헤어 퍼퓸 미스트 우디",
    brand: "어뮤즈",
    type: "woody",
    priceRange: "4~10만원",
    price: "32,000원",
    originalPrice: 32000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 어뮤즈 헤어 퍼퓸 미스트 우디입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P106",
    name: "어뮤즈 헤어 퍼퓸 미스트 시트러스",
    brand: "어뮤즈",
    type: "citrus",
    priceRange: "4~10만원",
    price: "32,000원",
    originalPrice: 32000,
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 어뮤즈 헤어 퍼퓸 미스트 시트러스입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P107",
    name: "벨벳바니 스킨퍼퓸 화이트 머스크",
    brand: "벨벳바니",
    type: "musk",
    priceRange: "1~3만원",
    price: "29,800원",
    originalPrice: 29800,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 벨벳바니 스킨퍼퓸 화이트 머스크입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P108",
    name: "벨벳바니 스킨퍼퓸 피치 플로럴",
    brand: "벨벳바니",
    type: "floral",
    priceRange: "1~3만원",
    price: "29,800원",
    originalPrice: 29800,
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 벨벳바니 스킨퍼퓸 피치 플로럴입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P109",
    name: "벨벳바니 스킨퍼퓸 코튼 클린",
    brand: "벨벳바니",
    type: "musk",
    priceRange: "1~3만원",
    price: "29,800원",
    originalPrice: 29800,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 벨벳바니 스킨퍼퓸 코튼 클린입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P110",
    name: "벨벳바니 스킨퍼퓸 로즈 블룸",
    brand: "벨벳바니",
    type: "floral",
    priceRange: "1~3만원",
    price: "29,800원",
    originalPrice: 29800,
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 벨벳바니 스킨퍼퓸 로즈 블룸입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P111",
    name: "벨벳바니 스킨퍼퓸 시트러스 샤워",
    brand: "벨벳바니",
    type: "citrus",
    priceRange: "1~3만원",
    price: "29,800원",
    originalPrice: 29800,
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 벨벳바니 스킨퍼퓸 시트러스 샤워입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P112",
    name: "헉슬리 퍼퓸 모로칸 가드너",
    brand: "헉슬리",
    type: "oriental",
    priceRange: "4~10만원",
    price: "38,000원",
    originalPrice: 38000,
    top: "스파이스, 만다린",
    middle: "바닐라, 플로럴",
    base: "앰버, 머스크",
    situation: "저녁/특별한 날",
    description:
      "오리엔탈 계열의 헉슬리 퍼퓸 모로칸 가드너입니다. 저녁/특별한 날 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P113",
    name: "헉슬리 퍼퓸 블루 메디나 탠저린",
    brand: "헉슬리",
    type: "citrus",
    priceRange: "4~10만원",
    price: "38,000원",
    originalPrice: 38000,
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 헉슬리 퍼퓸 블루 메디나 탠저린입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P114",
    name: "헉슬리 퍼퓸 포트브레스",
    brand: "헉슬리",
    type: "floral",
    priceRange: "4~10만원",
    price: "38,000원",
    originalPrice: 38000,
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 헉슬리 퍼퓸 포트브레스입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P115",
    name: "헉슬리 퍼퓸 베르베르 포트레이트",
    brand: "헉슬리",
    type: "woody",
    priceRange: "4~10만원",
    price: "38,000원",
    originalPrice: 38000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 헉슬리 퍼퓸 베르베르 포트레이트입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P116",
    name: "헉슬리 퍼퓸 선셋 포그",
    brand: "헉슬리",
    type: "citrus",
    priceRange: "4~10만원",
    price: "38,000원",
    originalPrice: 38000,
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 헉슬리 퍼퓸 선셋 포그입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P117",
    name: "헉슬리 헤어퍼퓸 모로칸 가드너",
    brand: "헉슬리",
    type: "floral",
    priceRange: "4~10만원",
    price: "38,000원",
    originalPrice: 38000,
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 헉슬리 헤어퍼퓸 모로칸 가드너입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P118",
    name: "헉슬리 헤어퍼퓸 블루 메디나 탠저린",
    brand: "헉슬리",
    type: "citrus",
    priceRange: "4~10만원",
    price: "38,000원",
    originalPrice: 38000,
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 헉슬리 헤어퍼퓸 블루 메디나 탠저린입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P119",
    name: "헉슬리 헤어퍼퓸 포트브레스",
    brand: "헉슬리",
    type: "oriental",
    priceRange: "4~10만원",
    price: "38,000원",
    originalPrice: 38000,
    top: "스파이스, 만다린",
    middle: "바닐라, 플로럴",
    base: "앰버, 머스크",
    situation: "저녁/특별한 날",
    description:
      "오리엔탈 계열의 헉슬리 헤어퍼퓸 포트브레스입니다. 저녁/특별한 날 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P120",
    name: "지미추 EDT",
    brand: "지미추",
    type: "woody",
    priceRange: "10만원 이상",
    price: "113,000원",
    originalPrice: 113000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 지미추 EDT입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P121",
    name: "지미추 EDP",
    brand: "지미추",
    type: "citrus",
    priceRange: "10만원 이상",
    price: "113,000원",
    originalPrice: 113000,
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 지미추 EDP입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P122",
    name: "지미추 아이 원 추 EDP",
    brand: "지미추",
    type: "oriental",
    priceRange: "10만원 이상",
    price: "113,000원",
    originalPrice: 113000,
    top: "스파이스, 만다린",
    middle: "바닐라, 플로럴",
    base: "앰버, 머스크",
    situation: "저녁/특별한 날",
    description:
      "오리엔탈 계열의 지미추 아이 원 추 EDP입니다. 저녁/특별한 날 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P123",
    name: "지미추 맨 EDT",
    brand: "지미추",
    type: "woody",
    priceRange: "10만원 이상",
    price: "113,000원",
    originalPrice: 113000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 지미추 맨 EDT입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P124",
    name: "지미추 블로썸 EDP",
    brand: "지미추",
    type: "musk",
    priceRange: "10만원 이상",
    price: "113,000원",
    originalPrice: 113000,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 지미추 블로썸 EDP입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P125",
    name: "누다라 EDP 틴타슈",
    brand: "누다라",
    type: "oriental",
    priceRange: "4~10만원",
    price: "52,000원",
    originalPrice: 52000,
    top: "스파이스, 만다린",
    middle: "바닐라, 플로럴",
    base: "앰버, 머스크",
    situation: "저녁/특별한 날",
    description:
      "오리엔탈 계열의 누다라 EDP 틴타슈입니다. 저녁/특별한 날 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P126",
    name: "누다라 EDP 피가로",
    brand: "누다라",
    type: "floral",
    priceRange: "4~10만원",
    price: "52,000원",
    originalPrice: 52000,
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 누다라 EDP 피가로입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P127",
    name: "누다라 EDP 하버",
    brand: "누다라",
    type: "floral",
    priceRange: "4~10만원",
    price: "52,000원",
    originalPrice: 52000,
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 누다라 EDP 하버입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P128",
    name: "누다라 EDP 피에르",
    brand: "누다라",
    type: "woody",
    priceRange: "4~10만원",
    price: "52,000원",
    originalPrice: 52000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 누다라 EDP 피에르입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P129",
    name: "누다라 EDP 무화과",
    brand: "누다라",
    type: "musk",
    priceRange: "4~10만원",
    price: "52,000원",
    originalPrice: 52000,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 누다라 EDP 무화과입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P130",
    name: "누다라 EDP 네롤리",
    brand: "누다라",
    type: "musk",
    priceRange: "4~10만원",
    price: "52,000원",
    originalPrice: 52000,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 누다라 EDP 네롤리입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P131",
    name: "아프리모 더바디 포 맨 EDP",
    brand: "아프리모",
    type: "woody",
    priceRange: "4~10만원",
    price: "73,000원",
    originalPrice: 73000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 아프리모 더바디 포 맨 EDP입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P132",
    name: "아프리모 더바디 포 우먼 EDP",
    brand: "아프리모",
    type: "citrus",
    priceRange: "4~10만원",
    price: "73,000원",
    originalPrice: 73000,
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 아프리모 더바디 포 우먼 EDP입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P133",
    name: "아프리모 핫스터프 EDP",
    brand: "아프리모",
    type: "musk",
    priceRange: "4~10만원",
    price: "73,000원",
    originalPrice: 73000,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 아프리모 핫스터프 EDP입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P134",
    name: "아프리모 미드나잇 EDP",
    brand: "아프리모",
    type: "oriental",
    priceRange: "4~10만원",
    price: "73,000원",
    originalPrice: 73000,
    top: "스파이스, 만다린",
    middle: "바닐라, 플로럴",
    base: "앰버, 머스크",
    situation: "저녁/특별한 날",
    description:
      "오리엔탈 계열의 아프리모 미드나잇 EDP입니다. 저녁/특별한 날 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P135",
    name: "아프리모 로맨스 EDP",
    brand: "아프리모",
    type: "woody",
    priceRange: "4~10만원",
    price: "73,000원",
    originalPrice: 73000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 아프리모 로맨스 EDP입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P136",
    name: "클린 EDP 웜코튼",
    brand: "클린",
    type: "musk",
    priceRange: "10만원 이상",
    price: "105,000원",
    originalPrice: 105000,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 클린 EDP 웜코튼입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P137",
    name: "클린 EDP 쿨코튼",
    brand: "클린",
    type: "musk",
    priceRange: "10만원 이상",
    price: "105,000원",
    originalPrice: 105000,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 클린 EDP 쿨코튼입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P138",
    name: "클린 EDP 레인",
    brand: "클린",
    type: "musk",
    priceRange: "10만원 이상",
    price: "105,000원",
    originalPrice: 105000,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 클린 EDP 레인입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P139",
    name: "클린 EDP 소프트 런드리",
    brand: "클린",
    type: "musk",
    priceRange: "10만원 이상",
    price: "105,000원",
    originalPrice: 105000,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 클린 EDP 소프트 런드리입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P140",
    name: "클린 EDP 퓨어 솝",
    brand: "클린",
    type: "musk",
    priceRange: "10만원 이상",
    price: "105,000원",
    originalPrice: 105000,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 클린 EDP 퓨어 솝입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P141",
    name: "클린 EDP 스킨",
    brand: "클린",
    type: "musk",
    priceRange: "10만원 이상",
    price: "105,000원",
    originalPrice: 105000,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 클린 EDP 스킨입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P142",
    name: "클린 EDP 샤워 프레시",
    brand: "클린",
    type: "musk",
    priceRange: "10만원 이상",
    price: "105,000원",
    originalPrice: 105000,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 클린 EDP 샤워 프레시입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P143",
    name: "클린 EDP 플라워 프레시",
    brand: "클린",
    type: "floral",
    priceRange: "10만원 이상",
    price: "105,000원",
    originalPrice: 105000,
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 클린 EDP 플라워 프레시입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P144",
    name: "클린 EDP 리저브 블렌드",
    brand: "클린",
    type: "musk",
    priceRange: "10만원 이상",
    price: "105,000원",
    originalPrice: 105000,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 클린 EDP 리저브 블렌드입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P145",
    name: "클린 EDP 레인 30ml",
    brand: "클린",
    type: "musk",
    priceRange: "4~10만원",
    price: "60,000원",
    originalPrice: 60000,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 클린 EDP 레인 30ml입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P146",
    name: "클린 EDP 레인 60ml",
    brand: "클린",
    type: "musk",
    priceRange: "4~10만원",
    price: "60,000원",
    originalPrice: 60000,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 클린 EDP 레인 60ml입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P147",
    name: "클린 EDP 소프트 런드리 30ml",
    brand: "클린",
    type: "musk",
    priceRange: "4~10만원",
    price: "60,000원",
    originalPrice: 60000,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 클린 EDP 소프트 런드리 30ml입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P148",
    name: "클린 EDP 소프트 런드리 60ml",
    brand: "클린",
    type: "musk",
    priceRange: "4~10만원",
    price: "60,000원",
    originalPrice: 60000,
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 클린 EDP 소프트 런드리 60ml입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P149",
    name: "어스 EDP 윔비 포레스트",
    brand: "어스",
    type: "woody",
    priceRange: "4~10만원",
    price: "59,000원",
    originalPrice: 59000,
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 어스 EDP 윔비 포레스트입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P150",
    name: "어스 EDP 라벤더 인 릴리프",
    brand: "어스",
    type: "floral",
    priceRange: "4~10만원",
    price: "59,000원",
    originalPrice: 59000,
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 어스 EDP 라벤더 인 릴리프입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P151",
    name: "어스 EDP 아이리스 포레스트",
    brand: "어스",
    type: "floral",
    priceRange: "4~10만원",
    price: "59,000원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 어스 EDP 아이리스 포레스트입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P152",
    name: "어스 EDP 시더우드 블룸",
    brand: "어스",
    type: "woody",
    priceRange: "4~10만원",
    price: "59,000원",
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 어스 EDP 시더우드 블룸입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P153",
    name: "어스 EDP 그린 머스크",
    brand: "어스",
    type: "musk",
    priceRange: "4~10만원",
    price: "59,000원",
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 어스 EDP 그린 머스크입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P154",
    name: "로에 EDP 화이트 셔츠",
    brand: "로에",
    type: "musk",
    priceRange: "4~10만원",
    price: "48,000원",
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 로에 EDP 화이트 셔츠입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P155",
    name: "로에 EDP 러브 피치",
    brand: "로에",
    type: "floral",
    priceRange: "4~10만원",
    price: "48,000원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 로에 EDP 러브 피치입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P156",
    name: "로에 EDP 베르가못 샤워",
    brand: "로에",
    type: "citrus",
    priceRange: "4~10만원",
    price: "48,000원",
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 로에 EDP 베르가못 샤워입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P157",
    name: "로에 EDP 우디 라운지",
    brand: "로에",
    type: "woody",
    priceRange: "4~10만원",
    price: "48,000원",
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 로에 EDP 우디 라운지입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P158",
    name: "로에 EDP 바닐라 머스크",
    brand: "로에",
    type: "oriental",
    priceRange: "4~10만원",
    price: "48,000원",
    top: "스파이스, 만다린",
    middle: "바닐라, 플로럴",
    base: "앰버, 머스크",
    situation: "저녁/특별한 날",
    description:
      "오리엔탈 계열의 로에 EDP 바닐라 머스크입니다. 저녁/특별한 날 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P159",
    name: "더블유드레스룸 드레스퍼퓸 No.49 피치블러썸",
    brand: "더블유드레스룸",
    type: "floral",
    priceRange: "1~3만원",
    price: "12,900원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 더블유드레스룸 드레스퍼퓸 No.49 피치블러썸입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P160",
    name: "더블유드레스룸 드레스퍼퓸 No.97 에이프릴코튼",
    brand: "더블유드레스룸",
    type: "musk",
    priceRange: "1~3만원",
    price: "12,900원",
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 더블유드레스룸 드레스퍼퓸 No.97 에이프릴코튼입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P161",
    name: "더블유드레스룸 드레스퍼퓸 No.45 모닝레인",
    brand: "더블유드레스룸",
    type: "citrus",
    priceRange: "1~3만원",
    price: "12,900원",
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 더블유드레스룸 드레스퍼퓸 No.45 모닝레인입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P162",
    name: "더블유드레스룸 드레스퍼퓸 No.11 화이트솝",
    brand: "더블유드레스룸",
    type: "musk",
    priceRange: "1~3만원",
    price: "12,900원",
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 더블유드레스룸 드레스퍼퓸 No.11 화이트솝입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P163",
    name: "더블유드레스룸 드레스퍼퓸 No.34 올웨이즈해피",
    brand: "더블유드레스룸",
    type: "citrus",
    priceRange: "1~3만원",
    price: "12,900원",
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 더블유드레스룸 드레스퍼퓸 No.34 올웨이즈해피입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P164",
    name: "더블유드레스룸 드레스퍼퓸 No.98 시크앰버",
    brand: "더블유드레스룸",
    type: "oriental",
    priceRange: "1~3만원",
    price: "12,900원",
    top: "스파이스, 만다린",
    middle: "바닐라, 플로럴",
    base: "앰버, 머스크",
    situation: "저녁/특별한 날",
    description:
      "오리엔탈 계열의 더블유드레스룸 드레스퍼퓸 No.98 시크앰버입니다. 저녁/특별한 날 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P165",
    name: "더블유드레스룸 드레스퍼퓸 No.43 포레스트워킹",
    brand: "더블유드레스룸",
    type: "woody",
    priceRange: "1~3만원",
    price: "12,900원",
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 더블유드레스룸 드레스퍼퓸 No.43 포레스트워킹입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P166",
    name: "베르사체 브라이트 크리스탈 EDT",
    brand: "베르사체",
    type: "floral",
    priceRange: "10만원 이상",
    price: "118,000원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 베르사체 브라이트 크리스탈 EDT입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P167",
    name: "베르사체 딜런 블루 EDT",
    brand: "베르사체",
    type: "woody",
    priceRange: "10만원 이상",
    price: "118,000원",
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 베르사체 딜런 블루 EDT입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P168",
    name: "베르사체 에로스 EDT",
    brand: "베르사체",
    type: "oriental",
    priceRange: "10만원 이상",
    price: "118,000원",
    top: "스파이스, 만다린",
    middle: "바닐라, 플로럴",
    base: "앰버, 머스크",
    situation: "저녁/특별한 날",
    description:
      "오리엔탈 계열의 베르사체 에로스 EDT입니다. 저녁/특별한 날 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P169",
    name: "베르사체 뿌르옴므 EDT",
    brand: "베르사체",
    type: "citrus",
    priceRange: "10만원 이상",
    price: "118,000원",
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 베르사체 뿌르옴므 EDT입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P170",
    name: "베르사체 옐로우 다이아몬드 EDT",
    brand: "베르사체",
    type: "floral",
    priceRange: "10만원 이상",
    price: "118,000원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 베르사체 옐로우 다이아몬드 EDT입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P171",
    name: "바디판타지 바디스프레이 웨딩데이",
    brand: "바디판타지",
    type: "floral",
    priceRange: "1~3만원",
    price: "16,900원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 바디판타지 바디스프레이 웨딩데이입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P172",
    name: "바디판타지 바디스프레이 퓨어솝",
    brand: "바디판타지",
    type: "musk",
    priceRange: "1~3만원",
    price: "16,900원",
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 바디판타지 바디스프레이 퓨어솝입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P173",
    name: "바디판타지 바디스프레이 프레시화이트머스크",
    brand: "바디판타지",
    type: "musk",
    priceRange: "1~3만원",
    price: "16,900원",
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 바디판타지 바디스프레이 프레시화이트머스크입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P174",
    name: "바디판타지 바디스프레이 핑크스위트피",
    brand: "바디판타지",
    type: "floral",
    priceRange: "1~3만원",
    price: "16,900원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 바디판타지 바디스프레이 핑크스위트피입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P175",
    name: "바디판타지 바디스프레이 레몬소르베",
    brand: "바디판타지",
    type: "citrus",
    priceRange: "1~3만원",
    price: "16,900원",
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 바디판타지 바디스프레이 레몬소르베입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P176",
    name: "바디판타지 바디스프레이 바닐라",
    brand: "바디판타지",
    type: "oriental",
    priceRange: "1~3만원",
    price: "16,900원",
    top: "스파이스, 만다린",
    middle: "바닐라, 플로럴",
    base: "앰버, 머스크",
    situation: "저녁/특별한 날",
    description:
      "오리엔탈 계열의 바디판타지 바디스프레이 바닐라입니다. 저녁/특별한 날 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P177",
    name: "바디판타지 바디스프레이 코튼캔디",
    brand: "바디판타지",
    type: "oriental",
    priceRange: "1~3만원",
    price: "16,900원",
    top: "스파이스, 만다린",
    middle: "바닐라, 플로럴",
    base: "앰버, 머스크",
    situation: "저녁/특별한 날",
    description:
      "오리엔탈 계열의 바디판타지 바디스프레이 코튼캔디입니다. 저녁/특별한 날 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P178",
    name: "아리아나그란데 클라우드 EDP",
    brand: "아리아나그란데",
    type: "musk",
    priceRange: "10만원 이상",
    price: "109,000원",
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 아리아나그란데 클라우드 EDP입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P179",
    name: "아리아나그란데 스위트 라이크 캔디 EDP",
    brand: "아리아나그란데",
    type: "oriental",
    priceRange: "10만원 이상",
    price: "109,000원",
    top: "스파이스, 만다린",
    middle: "바닐라, 플로럴",
    base: "앰버, 머스크",
    situation: "저녁/특별한 날",
    description:
      "오리엔탈 계열의 아리아나그란데 스위트 라이크 캔디 EDP입니다. 저녁/특별한 날 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P180",
    name: "아리아나그란데 문라이트 EDP",
    brand: "아리아나그란데",
    type: "floral",
    priceRange: "10만원 이상",
    price: "109,000원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 아리아나그란데 문라이트 EDP입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P181",
    name: "아리아나그란데 땡큐 넥스트 EDP",
    brand: "아리아나그란데",
    type: "oriental",
    priceRange: "10만원 이상",
    price: "109,000원",
    top: "스파이스, 만다린",
    middle: "바닐라, 플로럴",
    base: "앰버, 머스크",
    situation: "저녁/특별한 날",
    description:
      "오리엔탈 계열의 아리아나그란데 땡큐 넥스트 EDP입니다. 저녁/특별한 날 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P182",
    name: "아리아나그란데 아리 EDP",
    brand: "아리아나그란데",
    type: "floral",
    priceRange: "10만원 이상",
    price: "109,000원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 아리아나그란데 아리 EDP입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P183",
    name: "코치 플로럴 EDP",
    brand: "코치",
    type: "floral",
    priceRange: "10만원 이상",
    price: "105,000원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 코치 플로럴 EDP입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P184",
    name: "코치 맨 EDT",
    brand: "코치",
    type: "woody",
    priceRange: "10만원 이상",
    price: "105,000원",
    top: "베르가못",
    middle: "세이지, 라벤더",
    base: "시더우드, 샌달우드",
    situation: "출근/격식",
    description:
      "우디 계열의 코치 맨 EDT입니다. 출근/격식 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P185",
    name: "코치 드림스 EDP",
    brand: "코치",
    type: "citrus",
    priceRange: "10만원 이상",
    price: "105,000원",
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 코치 드림스 EDP입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P186",
    name: "코치 오 드 퍼퓸",
    brand: "코치",
    type: "floral",
    priceRange: "10만원 이상",
    price: "105,000원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 코치 오 드 퍼퓸입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P187",
    name: "코치 블루 EDT",
    brand: "코치",
    type: "citrus",
    priceRange: "10만원 이상",
    price: "105,000원",
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 코치 블루 EDT입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P188",
    name: "필로소피 어메이징 그레이스 EDT",
    brand: "필로소피",
    type: "musk",
    priceRange: "4~10만원",
    price: "65,000원",
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 필로소피 어메이징 그레이스 EDT입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P189",
    name: "필로소피 퓨어 그레이스 EDT",
    brand: "필로소피",
    type: "musk",
    priceRange: "4~10만원",
    price: "65,000원",
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 필로소피 퓨어 그레이스 EDT입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P190",
    name: "필로소피 프레시 크림 EDT",
    brand: "필로소피",
    type: "oriental",
    priceRange: "4~10만원",
    price: "65,000원",
    top: "스파이스, 만다린",
    middle: "바닐라, 플로럴",
    base: "앰버, 머스크",
    situation: "저녁/특별한 날",
    description:
      "오리엔탈 계열의 필로소피 프레시 크림 EDT입니다. 저녁/특별한 날 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P191",
    name: "필로소피 리빙 그레이스 EDT",
    brand: "필로소피",
    type: "citrus",
    priceRange: "4~10만원",
    price: "65,000원",
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 필로소피 리빙 그레이스 EDT입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P192",
    name: "안나수이 시크릿 위시 EDT",
    brand: "안나수이",
    type: "citrus",
    priceRange: "4~10만원",
    price: "78,000원",
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 안나수이 시크릿 위시 EDT입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P193",
    name: "안나수이 라비 드 보헴 EDT",
    brand: "안나수이",
    type: "floral",
    priceRange: "4~10만원",
    price: "78,000원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 안나수이 라비 드 보헴 EDT입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P194",
    name: "안나수이 스카이 EDT",
    brand: "안나수이",
    type: "musk",
    priceRange: "4~10만원",
    price: "78,000원",
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 안나수이 스카이 EDT입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P195",
    name: "안나수이 판타지아 EDT",
    brand: "안나수이",
    type: "oriental",
    priceRange: "4~10만원",
    price: "78,000원",
    top: "스파이스, 만다린",
    middle: "바닐라, 플로럴",
    base: "앰버, 머스크",
    situation: "저녁/특별한 날",
    description:
      "오리엔탈 계열의 안나수이 판타지아 EDT입니다. 저녁/특별한 날 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P196",
    name: "안나수이 로맨티카 EDT",
    brand: "안나수이",
    type: "floral",
    priceRange: "4~10만원",
    price: "78,000원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 안나수이 로맨티카 EDT입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P197",
    name: "버버리 브릿 쉬어 EDT",
    brand: "버버리",
    type: "floral",
    priceRange: "10만원 이상",
    price: "115,000원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 버버리 브릿 쉬어 EDT입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P198",
    name: "버버리 터치 포 우먼 EDP",
    brand: "버버리",
    type: "musk",
    priceRange: "10만원 이상",
    price: "115,000원",
    top: "파우더, 코튼",
    middle: "아이리스, 클린 어코드",
    base: "화이트 머스크",
    situation: "데일리/첫 향수",
    description:
      "머스크 계열의 버버리 터치 포 우먼 EDP입니다. 데일리/첫 향수 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P199",
    name: "버버리 위크엔드 포 우먼 EDP",
    brand: "버버리",
    type: "citrus",
    priceRange: "10만원 이상",
    price: "115,000원",
    top: "레몬, 베르가못",
    middle: "네롤리, 그린티",
    base: "화이트 머스크",
    situation: "데일리/여름",
    description:
      "시트러스 계열의 버버리 위크엔드 포 우먼 EDP입니다. 데일리/여름 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
  {
    id: "P200",
    name: "버버리 허 EDP",
    brand: "버버리",
    type: "floral",
    priceRange: "10만원 이상",
    price: "115,000원",
    top: "배, 만다린",
    middle: "로즈, 자스민",
    base: "머스크",
    situation: "데이트/선물",
    description:
      "플로럴 계열의 버버리 허 EDP입니다. 데이트/선물 상황에 어울리는 향수로 추천할 수 있습니다.",
  },
];

export const perfumes = rawPerfumes.map((perfume) => ({
  ...perfume,
  oliveyoungLink: `https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=${encodeURIComponent(
    perfume.name
  )}`,
}));
